//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtherClient.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IHelloService")]
    public interface IHelloService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/AddInt", ReplyAction="http://tempuri.org/IHelloService/AddIntResponse")]
        int AddInt(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/AddInt", ReplyAction="http://tempuri.org/IHelloService/AddIntResponse")]
        System.Threading.Tasks.Task<int> AddIntAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetStudent", ReplyAction="http://tempuri.org/IHelloService/GetStudentResponse")]
        ClassLibrary.Student GetStudent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/GetStudent", ReplyAction="http://tempuri.org/IHelloService/GetStudentResponse")]
        System.Threading.Tasks.Task<ClassLibrary.Student> GetStudentAsync();
        
        // CODEGEN: 消息 CalculationRequest 的包装名称(CalculationRequest)以后生成的消息协定与默认值(ComputingNumbers)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/ComputingNumbers", ReplyAction="http://tempuri.org/IHelloService/ComputingNumbersResponse")]
        OtherClient.ServiceReference3.CallResultResponse ComputingNumbers(OtherClient.ServiceReference3.CalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloService/ComputingNumbers", ReplyAction="http://tempuri.org/IHelloService/ComputingNumbersResponse")]
        System.Threading.Tasks.Task<OtherClient.ServiceReference3.CallResultResponse> ComputingNumbersAsync(OtherClient.ServiceReference3.CalculationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculationRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int NumberA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int NumberB;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Operation;
        
        public CalculationRequest() {
        }
        
        public CalculationRequest(int NumberA, int NumberB, string Operation) {
            this.NumberA = NumberA;
            this.NumberB = NumberB;
            this.Operation = Operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CallResultResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CallResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ComputedResult;
        
        public CallResultResponse() {
        }
        
        public CallResultResponse(int ComputedResult) {
            this.ComputedResult = ComputedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloServiceChannel : OtherClient.ServiceReference3.IHelloService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceClient : System.ServiceModel.ClientBase<OtherClient.ServiceReference3.IHelloService>, OtherClient.ServiceReference3.IHelloService {
        
        public HelloServiceClient() {
        }
        
        public HelloServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddInt(int a, int b) {
            return base.Channel.AddInt(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddIntAsync(int a, int b) {
            return base.Channel.AddIntAsync(a, b);
        }
        
        public ClassLibrary.Student GetStudent() {
            return base.Channel.GetStudent();
        }
        
        public System.Threading.Tasks.Task<ClassLibrary.Student> GetStudentAsync() {
            return base.Channel.GetStudentAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtherClient.ServiceReference3.CallResultResponse OtherClient.ServiceReference3.IHelloService.ComputingNumbers(OtherClient.ServiceReference3.CalculationRequest request) {
            return base.Channel.ComputingNumbers(request);
        }
        
        public int ComputingNumbers(int NumberA, int NumberB, string Operation) {
            OtherClient.ServiceReference3.CalculationRequest inValue = new OtherClient.ServiceReference3.CalculationRequest();
            inValue.NumberA = NumberA;
            inValue.NumberB = NumberB;
            inValue.Operation = Operation;
            OtherClient.ServiceReference3.CallResultResponse retVal = ((OtherClient.ServiceReference3.IHelloService)(this)).ComputingNumbers(inValue);
            return retVal.ComputedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtherClient.ServiceReference3.CallResultResponse> OtherClient.ServiceReference3.IHelloService.ComputingNumbersAsync(OtherClient.ServiceReference3.CalculationRequest request) {
            return base.Channel.ComputingNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtherClient.ServiceReference3.CallResultResponse> ComputingNumbersAsync(int NumberA, int NumberB, string Operation) {
            OtherClient.ServiceReference3.CalculationRequest inValue = new OtherClient.ServiceReference3.CalculationRequest();
            inValue.NumberA = NumberA;
            inValue.NumberB = NumberB;
            inValue.Operation = Operation;
            return ((OtherClient.ServiceReference3.IHelloService)(this)).ComputingNumbersAsync(inValue);
        }
    }
}
