//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtherClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ICustomService")]
    public interface ICustomService {
        
        // CODEGEN: 操作 PostMessage 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/PostMessage", ReplyAction="http://tempuri.org/ICustomService/PostMessageResponse")]
        OtherClient.ServiceReference2.PostMessageResponse PostMessage(OtherClient.ServiceReference2.CarMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/PostMessage", ReplyAction="http://tempuri.org/ICustomService/PostMessageResponse")]
        System.Threading.Tasks.Task<OtherClient.ServiceReference2.PostMessageResponse> PostMessageAsync(OtherClient.ServiceReference2.CarMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/GetPerson", ReplyAction="http://tempuri.org/ICustomService/GetPersonResponse")]
        OtherClient.ServiceReference2.Person GetPerson(OtherClient.ServiceReference2.GetPersonRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/GetPerson", ReplyAction="http://tempuri.org/ICustomService/GetPersonResponse")]
        System.Threading.Tasks.Task<OtherClient.ServiceReference2.Person> GetPersonAsync(OtherClient.ServiceReference2.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/CheckRenpin", ReplyAction="http://tempuri.org/ICustomService/CheckRenpinResponse")]
        OtherClient.ServiceReference2.ResponseMessage CheckRenpin(OtherClient.ServiceReference2.RequestMessage request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/CheckRenpin", ReplyAction="http://tempuri.org/ICustomService/CheckRenpinResponse")]
        System.Threading.Tasks.Task<OtherClient.ServiceReference2.ResponseMessage> CheckRenpinAsync(OtherClient.ServiceReference2.RequestMessage request);
        
        // CODEGEN: 操作 SetWorkerInformation 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/SetWorkerInformation", ReplyAction="http://tempuri.org/ICustomService/SetWorkerInformationResponse")]
        OtherClient.ServiceReference2.SetWorkerInformationResponse SetWorkerInformation(OtherClient.ServiceReference2.Worker request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomService/SetWorkerInformation", ReplyAction="http://tempuri.org/ICustomService/SetWorkerInformationResponse")]
        System.Threading.Tasks.Task<OtherClient.ServiceReference2.SetWorkerInformationResponse> SetWorkerInformationAsync(OtherClient.ServiceReference2.Worker request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CarMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CarName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int MakeYear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SerType;
        
        public CarMessage() {
        }
        
        public CarMessage(string CarName, int MakeYear, string SerType) {
            this.CarName = CarName;
            this.MakeYear = MakeYear;
            this.SerType = SerType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMessageResponse {
        
        public PostMessageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        public GetPersonRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Person", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Person {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Address;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Zip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Age;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Name;
        
        public Person() {
        }
        
        public Person(string Address, string Zip, int Age, string Email, string Name) {
            this.Address = Address;
            this.Zip = Zip;
            this.Age = Age;
            this.Email = Email;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int MaxNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CheckName;
        
        public RequestMessage() {
        }
        
        public RequestMessage(int MaxNum, string CheckName) {
            this.MaxNum = MaxNum;
            this.CheckName = CheckName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResponseMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResponseMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int CheckResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Name;
        
        public ResponseMessage() {
        }
        
        public ResponseMessage(int CheckResult, string Name) {
            this.CheckResult = CheckResult;
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Worker", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Worker {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public ClassLibrary.ArtistInfo WorkerArtist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int WorkerAge;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string WorkerName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string WorkerNo;
        
        public Worker() {
        }
        
        public Worker(ClassLibrary.ArtistInfo WorkerArtist, int WorkerAge, string WorkerName, string WorkerNo) {
            this.WorkerArtist = WorkerArtist;
            this.WorkerAge = WorkerAge;
            this.WorkerName = WorkerName;
            this.WorkerNo = WorkerNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetWorkerInformationResponse {
        
        public SetWorkerInformationResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomServiceChannel : OtherClient.ServiceReference2.ICustomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomServiceClient : System.ServiceModel.ClientBase<OtherClient.ServiceReference2.ICustomService>, OtherClient.ServiceReference2.ICustomService {
        
        public CustomServiceClient() {
        }
        
        public CustomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtherClient.ServiceReference2.PostMessageResponse OtherClient.ServiceReference2.ICustomService.PostMessage(OtherClient.ServiceReference2.CarMessage request) {
            return base.Channel.PostMessage(request);
        }
        
        public void PostMessage(string CarName, int MakeYear, string SerType) {
            OtherClient.ServiceReference2.CarMessage inValue = new OtherClient.ServiceReference2.CarMessage();
            inValue.CarName = CarName;
            inValue.MakeYear = MakeYear;
            inValue.SerType = SerType;
            OtherClient.ServiceReference2.PostMessageResponse retVal = ((OtherClient.ServiceReference2.ICustomService)(this)).PostMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtherClient.ServiceReference2.PostMessageResponse> OtherClient.ServiceReference2.ICustomService.PostMessageAsync(OtherClient.ServiceReference2.CarMessage request) {
            return base.Channel.PostMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtherClient.ServiceReference2.PostMessageResponse> PostMessageAsync(string CarName, int MakeYear, string SerType) {
            OtherClient.ServiceReference2.CarMessage inValue = new OtherClient.ServiceReference2.CarMessage();
            inValue.CarName = CarName;
            inValue.MakeYear = MakeYear;
            inValue.SerType = SerType;
            return ((OtherClient.ServiceReference2.ICustomService)(this)).PostMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtherClient.ServiceReference2.Person OtherClient.ServiceReference2.ICustomService.GetPerson(OtherClient.ServiceReference2.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public string GetPerson(out string Zip, out int Age, out string Email, out string Name) {
            OtherClient.ServiceReference2.GetPersonRequest inValue = new OtherClient.ServiceReference2.GetPersonRequest();
            OtherClient.ServiceReference2.Person retVal = ((OtherClient.ServiceReference2.ICustomService)(this)).GetPerson(inValue);
            Zip = retVal.Zip;
            Age = retVal.Age;
            Email = retVal.Email;
            Name = retVal.Name;
            return retVal.Address;
        }
        
        public System.Threading.Tasks.Task<OtherClient.ServiceReference2.Person> GetPersonAsync(OtherClient.ServiceReference2.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtherClient.ServiceReference2.ResponseMessage OtherClient.ServiceReference2.ICustomService.CheckRenpin(OtherClient.ServiceReference2.RequestMessage request) {
            return base.Channel.CheckRenpin(request);
        }
        
        public int CheckRenpin(int MaxNum, string CheckName, out string Name) {
            OtherClient.ServiceReference2.RequestMessage inValue = new OtherClient.ServiceReference2.RequestMessage();
            inValue.MaxNum = MaxNum;
            inValue.CheckName = CheckName;
            OtherClient.ServiceReference2.ResponseMessage retVal = ((OtherClient.ServiceReference2.ICustomService)(this)).CheckRenpin(inValue);
            Name = retVal.Name;
            return retVal.CheckResult;
        }
        
        public System.Threading.Tasks.Task<OtherClient.ServiceReference2.ResponseMessage> CheckRenpinAsync(OtherClient.ServiceReference2.RequestMessage request) {
            return base.Channel.CheckRenpinAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OtherClient.ServiceReference2.SetWorkerInformationResponse OtherClient.ServiceReference2.ICustomService.SetWorkerInformation(OtherClient.ServiceReference2.Worker request) {
            return base.Channel.SetWorkerInformation(request);
        }
        
        public void SetWorkerInformation(ClassLibrary.ArtistInfo WorkerArtist, int WorkerAge, string WorkerName, string WorkerNo) {
            OtherClient.ServiceReference2.Worker inValue = new OtherClient.ServiceReference2.Worker();
            inValue.WorkerArtist = WorkerArtist;
            inValue.WorkerAge = WorkerAge;
            inValue.WorkerName = WorkerName;
            inValue.WorkerNo = WorkerNo;
            OtherClient.ServiceReference2.SetWorkerInformationResponse retVal = ((OtherClient.ServiceReference2.ICustomService)(this)).SetWorkerInformation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OtherClient.ServiceReference2.SetWorkerInformationResponse> OtherClient.ServiceReference2.ICustomService.SetWorkerInformationAsync(OtherClient.ServiceReference2.Worker request) {
            return base.Channel.SetWorkerInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<OtherClient.ServiceReference2.SetWorkerInformationResponse> SetWorkerInformationAsync(ClassLibrary.ArtistInfo WorkerArtist, int WorkerAge, string WorkerName, string WorkerNo) {
            OtherClient.ServiceReference2.Worker inValue = new OtherClient.ServiceReference2.Worker();
            inValue.WorkerArtist = WorkerArtist;
            inValue.WorkerAge = WorkerAge;
            inValue.WorkerName = WorkerName;
            inValue.WorkerNo = WorkerNo;
            return ((OtherClient.ServiceReference2.ICustomService)(this)).SetWorkerInformationAsync(inValue);
        }
    }
}
