//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddInt", ReplyAction="http://tempuri.org/IService/AddIntResponse")]
        int AddInt(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddInt", ReplyAction="http://tempuri.org/IService/AddIntResponse")]
        System.Threading.Tasks.Task<int> AddIntAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpLoadFile", ReplyAction="http://tempuri.org/IService/UpLoadFileResponse")]
        bool UpLoadFile(System.IO.Stream streamInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UpLoadFile", ReplyAction="http://tempuri.org/IService/UpLoadFileResponse")]
        System.Threading.Tasks.Task<bool> UpLoadFileAsync(System.IO.Stream streamInput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsFormClient.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsFormClient.ServiceReference1.IService>, WindowsFormClient.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddInt(int a, int b) {
            return base.Channel.AddInt(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddIntAsync(int a, int b) {
            return base.Channel.AddIntAsync(a, b);
        }
        
        public bool UpLoadFile(System.IO.Stream streamInput) {
            return base.Channel.UpLoadFile(streamInput);
        }
        
        public System.Threading.Tasks.Task<bool> UpLoadFileAsync(System.IO.Stream streamInput) {
            return base.Channel.UpLoadFileAsync(streamInput);
        }
    }
}
