//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormClient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IMyService_1", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMyService_1 {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMyService_1/SetValue")]
        void SetValue(int n);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMyService_1/SetValue")]
        System.Threading.Tasks.Task SetValueAsync(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService_1/GetValue", ReplyAction="http://tempuri.org/IMyService_1/GetValueResponse")]
        int GetValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService_1/GetValue", ReplyAction="http://tempuri.org/IMyService_1/GetValueResponse")]
        System.Threading.Tasks.Task<int> GetValueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyService_1Channel : WindowsFormClient.ServiceReference2.IMyService_1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyService_1Client : System.ServiceModel.ClientBase<WindowsFormClient.ServiceReference2.IMyService_1>, WindowsFormClient.ServiceReference2.IMyService_1 {
        
        public MyService_1Client() {
        }
        
        public MyService_1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyService_1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyService_1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyService_1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetValue(int n) {
            base.Channel.SetValue(n);
        }
        
        public System.Threading.Tasks.Task SetValueAsync(int n) {
            return base.Channel.SetValueAsync(n);
        }
        
        public int GetValue() {
            return base.Channel.GetValue();
        }
        
        public System.Threading.Tasks.Task<int> GetValueAsync() {
            return base.Channel.GetValueAsync();
        }
    }
}
