//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IMyService1")]
    public interface IMyService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService1/GetStudentInfo", ReplyAction="http://tempuri.org/IMyService1/GetStudentInfoResponse")]
        Service.Student GetStudentInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService1/GetStudentInfo", ReplyAction="http://tempuri.org/IMyService1/GetStudentInfoResponse")]
        System.Threading.Tasks.Task<Service.Student> GetStudentInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyService1Channel : Client.ServiceRef.IMyService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyService1Client : System.ServiceModel.ClientBase<Client.ServiceRef.IMyService1>, Client.ServiceRef.IMyService1 {
        
        public MyService1Client() {
        }
        
        public MyService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Service.Student GetStudentInfo() {
            return base.Channel.GetStudentInfo();
        }
        
        public System.Threading.Tasks.Task<Service.Student> GetStudentInfoAsync() {
            return base.Channel.GetStudentInfoAsync();
        }
    }
}
